export enum AssetsActionTypes {
    SET_ASSETS = 'SET_ASSETS',
    SET_ASSETS_BY_ID = 'SET_ASSETS_BY_ID',
    SET_ASSETS_HISTORY_BY_ID = 'SET_ASSETS_HISTORY_BY_ID',
    SET_ASSETS_MARKETS_BY_ID = 'SET_ASSETS_MARKETS_BY_ID',
    SET_ASSETS_TOP_3 = 'SET_ASSETS_TOP_3',
    SET_IS_FETCHING_CARD = 'SET_IS_FETCHING_CARD'
}