export enum AppActionsTypes {
    INITIALIZED_SUCCESS = 'INITIALIZED_SUCCESS',
    SET_FETCHING = 'SET_FETCHING',
    SET_ASSETS_OFFSET = 'SET_ASSETS_OFFSET',
    SET_ASSETS_LIMIT = 'SET_ASSETS_LIMIT',
    SET_ASSETS_LAST_RANK = 'SET_ASSETS_LAST_RANK',
    SET_APP_CURRENT_PAGE = 'SET_APP_CURRENT_PAGE'
}